# Generated by Django 3.0.2 on 2020-01-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator_data', models.CharField(max_length=500)),
                ('locator_id', models.CharField(max_length=200)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafetch_locator.MainClass')),
            ],
        ),
    ]
