# Generated by Django 3.0.2 on 2020-01-10 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch_locator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locator',
            old_name='locator',
            new_name='locator_id',
        ),
        migrations.AddField(
            model_name='locator',
            name='locator_data',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
