# Generated by Django 3.0.2 on 2020-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch_locator', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclass',
            name='layer_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
