# Generated by Django 3.0.2 on 2020-01-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datafetch_locator', '0002_auto_20200115_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayerConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_layer_name', models.CharField(max_length=200)),
                ('right_layer_name', models.CharField(max_length=200)),
                ('left_connect', models.CharField(max_length=200)),
                ('right_connect', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LayerValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatorData', models.CharField(max_length=500)),
                ('locator_id', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=5)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datafetch_locator.Layer')),
            ],
        ),
        migrations.DeleteModel(
            name='Locator',
        ),
        migrations.DeleteModel(
            name='MainClass',
        ),
    ]
